
#     create table
#   public."User" (
#     id bigint generated by default as identity,
#     created_at timestamp with time zone not null default now(),
#     profile character varying null,
#     status text null,
#     user_name character varying null,
#     email character varying null,
#     passcode character varying null,
#     saved_stories bigint[] null,
#     enabled boolean null,
#     constraint User_pkey primary key (id)
#   ) tablespace pg_default;

# create table
#   public."Story" (
#     id bigint generated by default as identity,
#     created_at timestamp with time zone not null default now(),
#     title text null,
#     description text null,
#     liked_by bigint null,
#     uploaded_by bigint null,
#     imgurl json null,
#     updated_at timestamp with time zone null,
#     category character varying null,
#     enabled boolean null default true,
#     constraint story_pkey primary key (id),
#     constraint Story_liked_by_fkey foreign key (liked_by) references "User" (id),
#     constraint Story_uploaded_by_fkey foreign key (uploaded_by) references "User" (id)
#   ) tablespace pg_default;

# create table
#   public."Comments" (
#     id bigint generated by default as identity,
#     created_at timestamp with time zone not null default now(),
#     commented_by bigint null,
#     storyid bigint null,
#     type text null,
#     description text null,
#     enabled boolean null,
#     constraint Comments_pkey primary key (id),
#     constraint Comments_commented_by_fkey foreign key (commented_by) references "User" (id),
#     constraint Comments_storyid_fkey foreign key (storyid) references "Story" (id)
#   ) tablespace pg_default;