
#     create table
#   public."User" (
#     id bigint generated by default as identity,
#     created_at timestamp with time zone not null default now(),
#     profile character varying null,
#     status text null,
#     user_name character varying null,
#     email character varying null,
#     passcode character varying null,
#     saved_stories bigint[] null,
#     enabled boolean null,
#     constraint User_pkey primary key (id)
#   ) tablespace pg_default;

